name: my_manga_h
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons:
  google_fonts:
  jiffy:
  logger:
  flutter_drawing_board:
  hive:
  path_provider:
  hive_flutter:
  image_picker:
  flutter_colorpicker: ^1.1.0
  image: ^4.1.4
  fluttertoast: ^8.2.12
  url_launcher: ^6.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  hive_generator:
  build_runner:
  flutter_launcher_icons:


flutter:
  assets:
    - assets/images/
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"

fonts:
  - family: CustomsIcons
    fonts:
      -asset: fonts/CustomsIcons.ttf

